using System.Reflection;
[assembly: AssemblyTitle("ClooToOpenGL")]
[assembly: AssemblyDescription("Template for programming parallel tasks with help of OpenCL and OpenGL")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("ClooToOpenGL")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.1.2")]
