using System.Reflection;
[assembly: AssemblyTitle("ClooToOpenTK")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("ClooToOpenTK")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("19.1.13")]
